# Generated by Django 3.2 on 2021-05-22 21:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='butceKoduM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Bütçe Kodu')),
                ('mudurluk', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Müdürlük')),
                ('euro', models.FloatField(verbose_name='Euro')),
                ('ds', models.CharField(blank=True, max_length=255, verbose_name='Tanım')),
            ],
            options={
                'verbose_name': 'Bütçe Kodu',
                'verbose_name_plural': 'Bütçe Kodları',
                'db_table': 'Bütçe Kodları',
            },
        ),
        migrations.CreateModel(
            name='fiyatM',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='SKU')),
                ('euro', models.FloatField(verbose_name='Euro')),
                ('ds', models.CharField(max_length=255, verbose_name='Tanım')),
            ],
            options={
                'verbose_name': 'Ürün Fiyatı',
                'verbose_name_plural': 'Ürün Fiyatları',
                'db_table': 'Ürün Fiyatları',
            },
        ),
        migrations.CreateModel(
            name='istihkaklarGrupM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField(unique=True, verbose_name='SKU')),
                ('grup', models.IntegerField(verbose_name='İstihkak Grubu')),
                ('beden', models.CharField(max_length=45, verbose_name='Beden')),
                ('frekans', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)], verbose_name='Frekans')),
                ('mudurluk', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Müdürlük No')),
                ('cinsiyet', models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın')], max_length=1)),
                ('ds', models.CharField(blank=True, max_length=255, null=True, verbose_name='Not')),
            ],
            options={
                'verbose_name': 'İstihkak Grubu',
                'verbose_name_plural': 'İstihkak Grupları',
                'db_table': 'İstihkak Grupları',
            },
        ),
        migrations.CreateModel(
            name='istihkakM',
            fields=[
                ('grup', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='İstihkak Grubu')),
                ('ds', models.CharField(max_length=255, verbose_name='Tanım')),
            ],
            options={
                'verbose_name': 'İstihkak',
                'verbose_name_plural': 'İstihkaklar',
                'db_table': 'İstihkak',
            },
        ),
        migrations.CreateModel(
            name='mudurlukM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mudurluk', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Müdürlük No')),
                ('ds', models.CharField(max_length=255, unique=True, verbose_name='Müdürlük İsmi')),
            ],
            options={
                'verbose_name': 'Müdürlük',
                'verbose_name_plural': 'Müdürlükler',
                'db_table': 'Müdürlükler',
            },
        ),
        migrations.CreateModel(
            name='personellerM',
            fields=[
                ('isno', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='İş Numarası')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Adresi')),
                ('isim', models.CharField(max_length=45, verbose_name='İsim')),
                ('soyisim', models.CharField(max_length=45, verbose_name='Soyisim')),
                ('tel', models.CharField(max_length=10, unique=True, verbose_name='Telefon (5012345678)')),
                ('rfid', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(1)], verbose_name='RFID')),
                ('mudurluk', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Müdürlük')),
                ('ilkamirlik', models.CharField(max_length=45, unique=True, verbose_name='İlk Amirlik')),
                ('cinsiyet', models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın')], max_length=1)),
                ('grup', models.CharField(max_length=45, unique=True, verbose_name='Grup')),
                ('ds', models.CharField(blank=True, max_length=255, null=True, verbose_name='Not')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
                'db_table': 'Personeller',
            },
        ),
        migrations.CreateModel(
            name='sarfKullanicilarM',
            fields=[
                ('isno', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='İş Numarası')),
                ('password', models.CharField(max_length=45, unique=True, verbose_name='Şifre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Adresi')),
                ('isim', models.CharField(max_length=45, verbose_name='İsim')),
                ('soyisim', models.CharField(max_length=45, verbose_name='Soyisim')),
                ('tel', models.CharField(max_length=10, unique=True, verbose_name='Telefon (5012345678)')),
                ('ds', models.CharField(blank=True, max_length=255, verbose_name='Not')),
            ],
            options={
                'verbose_name': 'Sarf Kullanıcı',
                'verbose_name_plural': 'Sarf Kullanıcılar',
                'db_table': 'Sarf Kullanıcılar',
            },
        ),
        migrations.CreateModel(
            name='skuM',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='SKU')),
                ('ds', models.CharField(max_length=255, verbose_name='Tanım')),
            ],
            options={
                'verbose_name': 'SKU Bilgisi',
                'verbose_name_plural': 'SKU Bilgileri',
                'db_table': 'SKU Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='urunlerGrupM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=45, verbose_name='Ürün İsmi')),
                ('istihkak', models.BooleanField(default=False, verbose_name='İstihkak Ürünü')),
                ('grup', models.IntegerField(blank=True, verbose_name='İstihkak Grubu')),
                ('sku', models.IntegerField(unique=True, verbose_name='SKU')),
                ('ds', models.CharField(blank=True, max_length=255, null=True, verbose_name='Not')),
            ],
            options={
                'verbose_name': 'ÜrünlerGrup Bilgisi',
                'verbose_name_plural': 'ÜrünlerGrup Bilgileri',
                'db_table': 'ÜrünlerGrup Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='urunHareketlerM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verilenadet', models.FloatField(verbose_name='Verilen Adet')),
                ('istenilenadet', models.FloatField(verbose_name='İstenilen Adet')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kull_isno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.sarfkullanicilarm')),
                ('per_isno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.personellerm')),
                ('urun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.urunlergrupm')),
            ],
            options={
                'verbose_name': 'Ürün Hareketi',
                'verbose_name_plural': 'Ürün Hareketleri',
                'db_table': 'Ürün Hareketleri',
            },
        ),
        migrations.CreateModel(
            name='bedenlerM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup', models.IntegerField(verbose_name='İstihkak Grubu')),
                ('beden', models.CharField(max_length=45, verbose_name='Beden')),
                ('ds', models.CharField(blank=True, max_length=255, verbose_name='Not')),
                ('isno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.personellerm')),
            ],
            options={
                'verbose_name': 'Beden',
                'verbose_name_plural': 'Bedenler',
                'db_table': 'Bedenler',
            },
        ),
    ]
