# Generated by Django 3.2 on 2021-04-12 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sarfKullanicilarM',
            fields=[
                ('isno', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='İş Numarası')),
                ('password', models.CharField(max_length=45, unique=True, verbose_name='Şifre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Adresi')),
                ('isim', models.CharField(max_length=45, verbose_name='İsim')),
                ('soyisim', models.CharField(max_length=45, verbose_name='Soyisim')),
                ('tel', models.CharField(max_length=10, unique=True, verbose_name='Telefon (5012345678)')),
                ('ds', models.CharField(max_length=255, verbose_name='Not')),
            ],
            options={
                'verbose_name': 'Sarf Kullanıcı',
                'verbose_name_plural': 'Sarf Kullanıcılar',
                'db_table': 'Sarf Kullanıcılar',
            },
        ),
    ]
