# Generated by Django 2.1.15 on 2021-08-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingproductm',
            name='order_id',
            field=models.CharField(max_length=12, null=True, verbose_name='Sipariş Numarası'),
        ),
    ]
