# Generated by Django 3.2 on 2021-04-12 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personellerM',
            fields=[
                ('isno', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='İş Numarası')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Adresi')),
                ('isim', models.CharField(max_length=45, verbose_name='İsim')),
                ('soyisim', models.CharField(max_length=45, verbose_name='Soyisim')),
                ('tel', models.CharField(max_length=10, unique=True, verbose_name='Telefon (5012345678)')),
                ('rfid', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(1)], verbose_name='RFID')),
                ('mudurluk', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(100)], verbose_name='Müdürlük')),
                ('ilkamirlik', models.CharField(max_length=45, unique=True, verbose_name='İlk Amirlik')),
                ('cinsiyet', models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın')], max_length=1)),
                ('grup', models.CharField(max_length=45, unique=True, verbose_name='Grup')),
                ('ds', models.CharField(max_length=255, verbose_name='Not')),
            ],
        ),
    ]
