# Generated by Django 3.2 on 2021-04-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_personellerm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarfkullanicilarm',
            name='ds',
            field=models.CharField(max_length=255, null=True, verbose_name='Not'),
        ),
    ]
