# Generated by Django 2.1.15 on 2021-08-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_pendingproductm_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingproductm',
            name='order_id',
            field=models.CharField(max_length=12, verbose_name='Sipariş Numarası'),
        ),
    ]
