# Generated by Django 2.1.15 on 2021-08-17 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_auto_20210817_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroupm',
            name='frequency',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(730), django.core.validators.MinValueValidator(1)], verbose_name='Frekans'),
        ),
    ]
