# Generated by Django 3.2 on 2021-04-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_alter_sarfkullanicilarm_ds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarfkullanicilarm',
            name='ds',
            field=models.CharField(blank=True, max_length=255, verbose_name='Not'),
        ),
    ]
