# Generated by Django 3.2 on 2021-05-31 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_auto_20210601_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personellerm',
            name='tel2',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MaxValueValidator(5999999999), django.core.validators.MinValueValidator(5000000000)], verbose_name='Telefon (5012345678)'),
        ),
    ]
