# Generated by Django 2.1.15 on 2021-09-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_auto_20210817_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemTransactionsM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField(unique=True, verbose_name='SKU')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(verbose_name='Adet')),
                ('iotype', models.BooleanField(verbose_name='İşlem Türü')),
                ('ds', models.CharField(max_length=255, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Ürün Hareketi',
                'verbose_name_plural': 'Ürün Hareketleri',
                'db_table': 'itemTransactionsM',
            },
        ),
        migrations.AlterModelOptions(
            name='givenproductm',
            options={'verbose_name': 'Verilen Ürün', 'verbose_name_plural': 'Verilen Ürünler'},
        ),
    ]
