# Generated by Django 3.2 on 2021-06-01 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_alter_personellerm_tel2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urunlergrupm',
            name='sku',
        ),
        migrations.AddField(
            model_name='urunlergrupm',
            name='beden',
            field=models.CharField(max_length=45, null=True, verbose_name='Beden'),
        ),
        migrations.AddField(
            model_name='urunlergrupm',
            name='frekans',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)], verbose_name='Frekans'),
        ),
        migrations.AddField(
            model_name='urunlergrupm',
            name='mudurluk',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Müdürlük No'),
        ),
    ]
