# Generated by Django 3.2 on 2021-04-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_alter_sarfkullanicilarm_ds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personellerm',
            options={'verbose_name': 'Personel', 'verbose_name_plural': 'Personeller'},
        ),
        migrations.AlterField(
            model_name='personellerm',
            name='ds',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Not'),
        ),
        migrations.AlterModelTable(
            name='personellerm',
            table='Personeller',
        ),
    ]
