# Generated by Django 3.2 on 2021-04-12 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_auto_20210413_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personellerm',
            name='mudurluk',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Müdürlük'),
        ),
    ]
