# Generated by Django 3.2 on 2021-06-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_auto_20210601_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urunlergrupm',
            name='beden',
        ),
        migrations.AddField(
            model_name='istihkaklargrupm',
            name='urunGrup',
            field=models.CharField(max_length=45, null=True, verbose_name='Ürün Grubu'),
        ),
    ]
