# Generated by Django 2.1.15 on 2021-09-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_auto_20210907_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocksM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField(unique=True, verbose_name='SKU')),
                ('amount', models.FloatField(verbose_name='Adet')),
                ('ds', models.CharField(max_length=255, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Stok Bilgisi',
                'verbose_name_plural': 'Stok Bilgileri',
                'db_table': 'stocksM',
            },
        ),
    ]
