# Generated by Django 2.1.15 on 2021-09-10 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_stocksm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtransactionsm',
            name='sku',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='skum',
            name='sku',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='stocksm',
            name='sku',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='SKU'),
        ),
    ]
