# Generated by Django 3.2 on 2021-04-12 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_alter_personellerm_mudurluk'),
    ]

    operations = [
        migrations.CreateModel(
            name='mudurlukM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mudurluk', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(100)], verbose_name='Müdürlük No')),
                ('ds', models.CharField(max_length=255, unique=True, verbose_name='Müdürlük İsmi')),
            ],
            options={
                'verbose_name': 'Müdürlük',
                'verbose_name_plural': 'Müdürlükler',
                'db_table': 'Müdürlükler',
            },
        ),
    ]
