# Generated by Django 3.2 on 2021-04-13 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_mudurlukm'),
    ]

    operations = [
        migrations.CreateModel(
            name='butceKoduM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(100)], verbose_name='Bütçe Kodu')),
                ('mudurluk', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(100)], verbose_name='Müdürlük')),
                ('euro', models.FloatField(verbose_name='Euro')),
                ('ds', models.CharField(max_length=255, verbose_name='Tanım')),
            ],
            options={
                'verbose_name': 'Bütçe Kodu',
                'verbose_name_plural': 'Bütçe Kodları',
                'db_table': 'Bütçe Kodları',
            },
        ),
        migrations.AlterField(
            model_name='mudurlukm',
            name='mudurluk',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Müdürlük No'),
        ),
    ]
