# Generated by Django 3.2 on 2021-06-03 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_auto_20210603_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunlergrupm',
            name='adet',
            field=models.FloatField(null=True, verbose_name='Alınabilecek Adet'),
        ),
        migrations.AlterField(
            model_name='urunlergrupm',
            name='frekans',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)], verbose_name='Frekans'),
        ),
        migrations.AlterField(
            model_name='urunlergrupm',
            name='mudurluk',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Müdürlük No'),
        ),
    ]
