# Generated by Django 3.2 on 2021-04-13 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0008_auto_20210413_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butcekodum',
            name='ds',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tanım'),
        ),
        migrations.AlterField(
            model_name='butcekodum',
            name='kod',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Bütçe Kodu'),
        ),
        migrations.AlterField(
            model_name='butcekodum',
            name='mudurluk',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Müdürlük'),
        ),
    ]
