# Generated by Django 3.2 on 2021-06-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0008_auto_20210603_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='personellerm',
            name='faceid',
            field=models.CharField(max_length=45, null=True, verbose_name='Face ID'),
        ),
    ]
