# Generated by Django 3.2 on 2021-04-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0009_auto_20210413_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butcekodum',
            name='ds',
            field=models.TextField(verbose_name='Tanım'),
        ),
    ]
