# Generated by Django 3.2 on 2021-06-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0010_auto_20210611_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personellerm',
            name='grup',
            field=models.IntegerField(null=True, verbose_name='İstihkak Grubu'),
        ),
    ]
