# Generated by Django 3.2 on 2021-04-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0010_alter_butcekodum_ds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butcekodum',
            name='ds',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tanım'),
        ),
    ]
