# Generated by Django 3.2 on 2021-06-10 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0011_alter_personellerm_grup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sarfkullanicilarm',
            name='password',
        ),
    ]
