# Generated by Django 3.2 on 2021-04-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0011_alter_butcekodum_ds'),
    ]

    operations = [
        migrations.CreateModel(
            name='skuM',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='SKU')),
                ('ds', models.CharField(max_length=255, verbose_name='Tanım')),
            ],
            options={
                'verbose_name': 'SKU Bilgisi',
                'verbose_name_plural': 'SKU Bilgileri',
                'db_table': 'SKU Bilgileri',
            },
        ),
    ]
