# Generated by Django 3.2 on 2021-04-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0013_istihkakm'),
    ]

    operations = [
        migrations.CreateModel(
            name='fiyatM',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='SKU')),
                ('euro', models.FloatField(verbose_name='Euro')),
                ('ds', models.CharField(max_length=255, verbose_name='Tanım')),
            ],
            options={
                'verbose_name': 'Ürün Fiyatı',
                'verbose_name_plural': 'Ürün Fiyatları',
                'db_table': 'Ürün Fiyatları',
            },
        ),
    ]
