# Generated by Django 3.2 on 2021-04-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0015_bedenlerm'),
    ]

    operations = [
        migrations.CreateModel(
            name='urunlerGrupM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=45, verbose_name='İsim')),
                ('istihkak', models.BooleanField(default=False, verbose_name='İstihkak Bilgisi')),
                ('grup', models.IntegerField(verbose_name='İstihkak Grubu')),
                ('sku', models.IntegerField(unique=True, verbose_name='SKU')),
                ('ds', models.CharField(blank=True, max_length=255, null=True, verbose_name='Not')),
            ],
            options={
                'verbose_name': 'ÜrünlerGrup Bilgisi',
                'verbose_name_plural': 'ÜrünlerGrup Bilgileri',
                'db_table': 'ÜrünlerGrup Bilgileri',
            },
        ),
        migrations.AlterField(
            model_name='bedenlerm',
            name='ds',
            field=models.CharField(blank=True, max_length=255, verbose_name='Not'),
        ),
    ]
