# Generated by Django 3.2 on 2021-04-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0016_auto_20210413_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunlergrupm',
            name='istihkak',
            field=models.BooleanField(verbose_name='İstihkak Ürünü'),
        ),
    ]
