# Generated by Django 3.2 on 2021-04-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0018_alter_urunlergrupm_istihkak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunlergrupm',
            name='isim',
            field=models.CharField(max_length=45, verbose_name='Ürün İsmi'),
        ),
    ]
