# Generated by Django 3.2 on 2021-04-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0019_alter_urunlergrupm_isim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunlergrupm',
            name='grup',
            field=models.IntegerField(blank=True, verbose_name='İstihkak Grubu'),
        ),
    ]
