# Generated by Django 3.2 on 2021-04-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0020_alter_urunlergrupm_grup'),
    ]

    operations = [
        migrations.CreateModel(
            name='urunHareketlerM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verilenadet', models.FloatField(verbose_name='Verilen Adet')),
                ('istenilenadet', models.FloatField(verbose_name='İstenilen Adet')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kull_isno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.sarfkullanicilarm')),
                ('per_isno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.personellerm')),
                ('urun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.urunlergrupm')),
            ],
            options={
                'verbose_name': 'Ürün Hareketi',
                'verbose_name_plural': 'Ürün Hareketleri',
                'db_table': 'Ürün Hareketleri',
            },
        ),
    ]
