# Generated by Django 3.2 on 2021-05-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0022_istihkaklargrupm'),
    ]

    operations = [
        migrations.AddField(
            model_name='personellerm',
            name='rfid2',
            field=models.CharField(max_length=12, null=True, verbose_name='rfid2'),
        ),
    ]
