# Generated by Django 3.2 on 2021-05-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0023_personellerm_rfid2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personellerm',
            name='rfid2',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='rfid2'),
        ),
    ]
