# Generated by Django 3.2.3 on 2021-05-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0025_alter_personellerm_rfid2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personellerm',
            name='rfid2',
        ),
    ]
